$(document).ready(function(){
    $('button').click(function(){
        $.post('https://dummy.restapiexample.com/api/v1/create',
        {
            name:'jay1',
            username:'Artemis',
            city:'nagpur',
            pincode:'441101',
            state:'maharashtra',
            country:'india'
        },
        function(result){
            $('.show').html(result)
        }
        )
    })
})